name: Deploy Receptor

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push imagen Docker
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/receptor-boletines-744416:$IMAGE_TAG .
          docker push $ECR_REGISTRY/receptor-boletines-744416:$IMAGE_TAG

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_SESSION_TOKEN
          script: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 910039462201.dkr.ecr.us-east-1.amazonaws.com
            docker pull 910039462201.dkr.ecr.us-east-1.amazonaws.com/emisor-boletines-744416:${{ github.sha }}
            docker stop emisor || true
            docker rm emisor || true
            docker run -d --name emisor -p 8000:8000 \
              -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
              -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
              -e AWS_DEFAULT_REGION=us-east-1 \
              910039462201.dkr.ecr.us-east-1.amazonaws.com/emisor-boletines-744416:${{ github.sha }}